spring:
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: "org.h2.Driver"
    username: "sa"
    password: "password"
  h2:
    console:
      enabled: true

  mail:
    host: "sandbox.smtp.mailtrap.io"
    port: 465
    username: "d5862e24a63004"
    password: "38dab1396797c1"
    from: "from@example.com"
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8081